
project_id = 'gtxjfmvnzrsuaxryffnt'

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions]
[functions.webpay-init]
verify_jwt = false

[functions.webpay-confirm]
verify_jwt = false

[functions.send-reservation-email]
verify_jwt = false
